apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-demo-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/abd-hadi/devsecops-demo-gitops.git
    targetRevision: main
    path: devsecops-demo-app

  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
