replicaCount: 2

image:
  repository: 676591241638.dkr.ecr.us-east-1.amazonaws.com/devsecops-demo-app
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

serviceAccount:
  create: false
