replicaCount: 2

image:
  repository: 676591241638.dkr.ecr.us-east-1.amazonaws.com/devsecops-demo-app
  tag: 1bfee565c0e7312681405ba78c2d91394e75e6ec
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

serviceAccount:
  create: false
