apiVersion: v1
kind: Service
metadata:
  name: {{ include "devsecops-demo-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devsecops-demo-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
